### ISSUE TITLE
There is already a reasonably popular language named Rune

### ISSUE THREAD

**Issue by offsetcyan** [google/rune#13]
[The Rune Programming Language](https://rune-rs.github.io/)

**Comment by waywardgeek** [comment]
This language predates the other one.  I had a language called L42 in a personal github repo, which I wrote before joining Google back in 2015.  In maybe 2016 or 2017, I renamed it to Rune, after reading the Go language reference and seeing their use of the term for glyphs.  My old Rune project sat in my repo for a year or so, until I had a chance to work on an internal compiler.  I lent Google the name Rune, and renamed my old project [not_rune](https://github.com/waywardgeek/not_rune).

So, I'll claim precedence.

**Comment by DrGo** [comment]
There is also Rune Lange https://en.wikipedia.org/wiki/Rune_Lange :)

**Comment by waywardgeek** [comment]
Nice.  I figure the odds of either Rune language taking off is low, and if one does, it will simply eclipse the other without causing much confusion.

**Comment by DrGo** [comment]
I actually like your Rune’s design decisions and innovations and I think it’s a worthwhile effort. The bar for wide adaption is much higher these days. People expect complete and portable standard libs, excellent tooling including dep management, testing, profiling, easy cross compilation etc, and ideally support by a big organization and a killer app written in the language. Still luck like in everything else in life is the ultimate decider. I admire your courage and strength in undertaking such a massive project. Best of luck 🤞🤞🤞🤞

**Comment by waywardgeek** [comment]
Thanks!  Our definition of success is having impact on the world, which can be done through influencing other languages to adopt some of Rune's features.  The world is full of skeptics.  I find the best way to overcome skepticism is working code demonstrating value.
