### ISSUE TITLE
Probably missing dependency during installation

### ISSUE THREAD

**Issue by RuneDominik** [google/rune#24]
Following the installation instructions in the `README`, during the "building rune"-step, I ran into a missing prerequisite. The `make` command in 

```
$ git clone https://github.com/google/rune.git
$ git clone https://github.com/pornin/CTTK.git
$ cp CTTK/inc/cttk.h CTTK
$ cd rune
$ make
```

resulted in 

```
clang -Wall -g -std=c11 -Wno-varargs -I../../CTTK -DRN_DEBUG -c array.c bigint.c io.c random.c
make[1]: clang: No such file or directory
```

This was off course easy fixable by installing `clang`. But since especially `clang-14` is specifically stated as prerequisite I wondered if this list is incomplete and `clang` should be added to the instructions, specifically expanding 

```
$ sudo apt-get install bison flex libgmp-dev clang-14
```

to 

```
$ sudo apt-get install bison flex libgmp-dev clang clang-14
```
or if this was a problem on my site. Happy to give further information or to extend the `README`.

**Comment by waywardgeek** [comment]
SGTM.  I've added clang as you suggest.

**Comment by tariqrahiman** [comment]
@waywardgeek  - In the steps for installation; 
$ cp CTTK/inc/cttk.h CTTK
$ cd rune
$ make

the make command gives an error as shown below. I completed all commands including the one from @RuneDominik  as well. But got stuck in this error

datadraw -h include/dedatabase.h database/Rune.dd
make: datadraw: No such file of directory
make: *** [Makefile:97: include/dedatabase.h] Error 127
